version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: nexus-mysql
      working_dir: /application
      volumes:
        - ./database:/application
      environment:
        - MYSQL_ROOT_PASSWORD=wagner@123
        - MYSQL_DATABASE=nexus
        - MYSQL_USER=root
        - MYSQL_PASSWORD=wagner@123
      ports:
        - "8005:3306"

    webserver:
      image: nginx:alpine
      container_name: nexus-webserver
      working_dir: /application
      volumes:
          - ./nexus-wp:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8073:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: nexus-php-fpm
      working_dir: /application
      volumes:
        - ./nexus-wp:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini

